### ISSUE TITLE
Make compatible with new release process

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/output-explorer#216] opened 2021-11-25 15:59 UTC
As we move to released files living on the jobserver html reports will no longer be on github to point to when creating a new report. We will need to allow for linking to html files on the jobserver.

A nice side effect of this is that as the new release process has released outputs (available to view by collaborators) and published outputs (available to view by all), we could tie this to making a report public vs a draft.

**Comment by rebkwok** [comment] 2022-03-11 11:22
Duplicate of #27

**Closed by rebkwok** 2022-03-11 11:22 UTC
